### ISSUE TITLE
Heretic: secret/exit linedef colour inconsistencies.

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#103]
Last thing I can think of for Heretic, after a lot of *testing*. If you're "done" working on it for now, I can try a patch tomorrow.

IMO none of these display as I would expect:

Linedefs of secret sectors:
- are never coloured if they are 2S and there is a height difference between the sectors front side and back side. Moving sectors (e.g. lifts) will show them coloured if the sector moves to the height of adjacent sectors, until it changes height again.
- are never coloured if they are flagged to show as 1S
- are never coloured if flagged to not show on the automap. Normally this is fine, but they aren't coloured even if IDDT is used. Also if you implement colouring secrets that have been found, I'd suggest the found-secret colour still shows on invisible linedefs.

Exit linedefs:
- switch type linedefs are never coloured if they are on a 2S line

Teleport linedefs work fine, and I haven't noticed any problems with doors that need keys. (I would hope not since key-coloured doors are in vanilla, but with Raven's code that doesn't mean too much!)

test wad:
[ht_linecolours.zip](https://github.com/JNechaevsky/international-doom/files/14352681/ht_linecolours.zip)

**Comment by JNechaevsky** [comment]
Ah, must be a drawing order and/or drawing logics. Have a look please, without hurry. Meanwhile, I'll try to focus on some possibly forgotten small remainings.
