### ISSUE TITLE
[Bug] Inter-Hexen: Key mappings reset when playing Deathkings

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#105]
Upon entering HexenDK, my customized keyboard setup is resetting to default.

PS: It's possible this happened since there were new config entries with the latest update. Is the port resetting key configs in such cases?

**Comment by JNechaevsky** [comment]
> PS: It's possible this happened since there were new config entries with the latest update. Is the port resetting key configs in such cases?

Looks likes it was. 😟

Sigh. I think I was able to caught it one or two times, but never was able to reproduce it properly. Recent [change](https://github.com/JNechaevsky/international-doom/commit/ecea575cfd5b519732f51ba1719e9aa095872b13) hopefull will fix it, I've tried to add/remove new controls and features variables, looks likes it's all fine.

**Comment by NightFright2k19** [comment]
Thanks! Surely stuff one wants to have working properly before an official release. ^^ Will resume my DK playtesting session, then. Fingers crossed!

**Comment by JNechaevsky** [comment]
And done! Once hexdd.wad loaded, a folder `hexdd.wad` will be created in `autoload` folder. Absolutely same way to other autoloads.

**Comment by Meerschweinmann** [comment]
> And done! Once hexdd.wad loaded, a folder `hexdd.wad` will be created in `autoload` folder. Absolutely same way to other autoloads.

Nice! Then i can put separate widescreen assets with deathkings title screen in Hexdd folder 😀👌

**Comment by NightFright2k19** [comment]
Um, I'm afraid it's still happening. Not completely, but for example my jump key is reset when I load a PWAD, in this case caldera.wad...

**Comment by JNechaevsky** [comment]
Please advice, does it happens every time new pwad is loaded or just randomly? I can't reproduce it on my side. 😕
Also, did you tried to update source code by `git pull`? I made some changes yesterday for Hexen so now it is possible to run on Linux. Not sure it was the case, but...

**Comment by NightFright2k19** [comment]
Update:
I compared now a recent back of inter-hexen.ini from yesterday. At least the following variables are reset (basically all which I changed from default):
```
key_flyup 
key_flydown
key_flycenter 
key_invleft 
key_invright 
key_useartifact
key_jump
key_buddha
```
This probably won't help much since it doesn't reveal anything new. It's a total reset.

**Comment by JNechaevsky** [comment]
Total maze, but thank you for suggestion any ways. 🤗 Could you please `git pull` again, I made small additional change for Hexen.

**Comment by NightFright2k19** [comment]
Thanks for keeping it up. I'll keep an eye on this and will report back in a few days. By then it should be clear whether it's fixed or not. Fingers crossed!

**Comment by JNechaevsky** [comment]
I was able to catch it, finally. Pretty odd steps:

1. Start a game normally.
2. Make a save in any slot.
3. Press `DEL` on saved slot, and then `Y`.
4.  Restart the game. Controls will reset to defaults.

Something went wrong with action confirming, for some reason keyboard binding reset is invoked.

**Comment by JNechaevsky** [comment]
Oh dammit, missing `break;` below [this line](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/mn_menu.c#L4770) was executing `M_ResetBinds()` two lines below! 🤤

**Comment by NightFright2k19** [comment]
Right, savegame deletion. I did that after finishing regular Hexen and then again after DK. Would explain why it didn't happen more than once after starting a new game. Never thought it might have anything to do with it...
