### ISSUE TITLE
KdiKdizd Demo desync

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#109]
Hi Julia.

I have found something that you won't find good :(

Unfortunately the attached KdiKdizd demo desyncs in the green acid area.
Tested Inter-DOOM versions were 7.1,7.3 and latest build from today.
I have deleted even my config and did not touch anything in the menu to be sure that it is not an failure of my config.

Woof and Crispy do the demo fine.

The 4files (2WAD,1DEH and the Demo lump) were put on the exe per drag and drop in all cases from the same source folder.

[KDiKDi13-342.zip](https://github.com/JNechaevsky/international-doom/files/14373950/KDiKDi13-342.zip)

**Comment by Meerschweinmann** [comment]
With inter-doom -file kdikdi_a.wad kdikdi_b.wad kdikdizd.deh -timedemo kdikdi13-342.lmp from the command line it desyncs too.

My hope was that the dehacked file would not be loaded per drag and drop.

**Comment by JNechaevsky** [comment]
Confirmed, thank you very much! Fortunately, it's not dehacked:
- In general, dehacked patches should be loaded as `-deh kdikdizd.deh`, i.e. not with `-file`.
- KdiKdizd doesn't need it, as it's included in wad file and loaded automatically.

It's a randomized powerups health, which is needed for floating. I need either to remove this feature, or investigate and try different approach, which will not modify their health.

**Comment by Meerschweinmann** [comment]
As Crispy does the demo fine you could compare what is different.

**Comment by Meerschweinmann** [comment]
And thank you for the hint with -deh. Was ist the same with the Vanilla exes? I use the commandline not so often these days. In the 90s i was more comfortable with it.

**Comment by JNechaevsky** [comment]
Not really needed to compare with Crispy, all I need to know is proper demo end, i.e. exit from level. 🙂 To don't spend a lot of time on watching demo, I have disabled vsync and using "demo fast-formward" key, it is playing demo as fast as possible.

**Comment by JNechaevsky** [comment]
> And thank you for the hint with -deh. Was it the same with the Vanilla exes?

Not exactly, vanilla doesn't have Dehacked support as modern ports. It was needed to run DOS Dehacked executable and apply patch to vanilla Doom executable. Good times!

**Comment by Meerschweinmann** [comment]
Ah, now it came back to my mind. You are correct. I had a dehacked DOS executable that edited the exe. That explains why i can not remember this -deh command line. I can remember that we made the Shotgun and Rocket Launcher really fast. That was fun back in the days. And our 486 PCs were to slow to show these fast weapons correct 😀 But even a Cyberdemon was killed nearly instantly with these weapons. Good times, and 30 years younger....

**Comment by JNechaevsky** [comment]
I'm not the right person to recommend how to live, but strictly from my experience - better live "here and now", but think about tomorrow. Meanwhile, I'm a-a-a-almost there. Demo is not working fine, and I have removed unsafe changes, but there is one small nitpick left - floating powerups now always appearing on same height:

<details>

https://github.com/JNechaevsky/international-doom/assets/21193394/27da652a-626c-4385-a3eb-0ef50a218eb1

</details>

Absolutely not critical, but not cool either, since earlier they were spawn at slightly random height.

**Comment by JNechaevsky** [comment]
That's fine! 😁

https://github.com/JNechaevsky/international-doom/assets/21193394/ccd94e6a-51b0-46e3-a250-9fd17ff7a7d4

**Comment by JNechaevsky** [comment]
All done! Thanks again, this was a very important case. Everything was fine with demos until some of powerups was used for complicated mapping tricks. I even decided not to dig in, as Esselfortium definitely knows some higher magic and apply some very complicated Dehacked things for mapping purposes. This also should improve farther compatibility for such cases. 🤗

**Comment by Meerschweinmann** [comment]
Hooray, i have to thank you too. And allright, Esselfortium does real magic with DOOM. I like her maps alot.
