### ISSUE TITLE
Hexen: crash on load game after death

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#116]
~~Can't reproduce but maybe you have an idea.~~ Was playing this wad: https://www.doomworld.com/idgames/levels/hexen/a-c/cent092b

Saved, died shortly after, pressing spacebar to reload crashed:

```
P_SetupLevel: MAP01 ("CENTROMERE"), loaded in 5 ms.
P_SetupLevel: MAP02 ("THE AMBUSH POINT"), loaded in 4 ms.
Corrupt save game: Segment [104] failed alignment check
```

Note that I was still on MAP01. 

After starting inter-hexen again the save worked fine, even after dying.

***

edit: OK got it to reproduce: start a new game with cent092b.wad and On Death Action set to "Last Save", quicksave, die, press space.

gdb doesn't give me anything useful.

**Comment by JNechaevsky** [comment]
Total kaboom 🤯, but should work fine now. Don't ask anything, save system in Hexen is a nightmare, like saving into temporal slot first and moving to normal one second. So, "on death action" should work properly with any save slot, not just first one.

Following case should also be fixed:
* Game started normally
* Go to MAP02 (via noclip, not idclev)
* Suicide and try to reload - because of incorrect save name, game was trying to load incorrect slot.

**Comment by JNechaevsky** [comment]
This is getting too annoying. After couple of attempts, I don't proceed any farther than either game is always trying to load first slot, or ignoring any slot at all. I'll try a bit more, but if nothing will changes, probably better to just remove this feature entirely as not working properly.

**Comment by kitchen-ace** [comment]
What's different about starting a new game right after you start the program and then loading it, vs. loading a game when no game is playing? Because if you do it the 2nd way, the load slot is changed:

* start the program
* start a new game
* save
* end your game from the options menu/F7
* load that game you just saved
* save a new game
* die
* you come back to life from whatever slot you loaded from

I couldn't find a proper fix either. As a hack adding `G_LoadGame(6);` to the end of G_DoSaveGame [here](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/g_game.c#L2268) kind of works, though this makes it so "Default Action" still loads your last save too.

Anyhow if you can't figure it out no problem, though maybe just comment out the existing on-death action code so someone can try it again later.

**Comment by kitchen-ace** [comment]
What about adding `GameLoadSlot = slot;` to the end of [G_SaveGame](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/g_game.c#L2249)? Is that too much of a hack?

**Comment by JNechaevsky** [comment]
This seems to do the trick, thank you! ❤️
I was thinking to make a copy of saved slot to another one (8th), but this is silly. My only extra though is - what to do, if this slot will be deleted? But shouldn't be a problem though. 

Any ways, should I add it now, or you have some extra plans for farther investigation? Will do as you say.

**Comment by kitchen-ace** [comment]
>Any ways, should I add it now, or you have some extra plans for farther investigation? Will do as you say.

Go ahead and add it if you're happy with that as a solution. Figuring out that one line took me way longer than it should have, I don't wanna touch it again if I don't have to!

>My only extra though is - what to do, if this slot will be deleted? But shouldn't be a problem though.

There is probably a way to check if the save file exists before loading it [here](https://github.com/JNechaevsky/international-doom/commit/f6ea31fa9fdfbbccbb03610d960e51836f34450f#diff-7890be5186b0591b0f02fb5812b38e89716c67126bcac78fe58eaccda2925703R493) right? I'll take a look at this another time.

**Comment by kitchen-ace** [comment]
Hah. Add it now then and we'll deal with the case where the save game is deleted another time.

**Comment by JNechaevsky** [comment]
Sure thing! It's not that how-swappable like in Doom or Heretic, but it's working. No need to rush, it's a straight finish release line. I would like to release everything on 8th March, mostly because of nice joke and nice date... 😀

**Comment by JNechaevsky** [comment]
Yep, it is.

**Comment by kitchen-ace** [comment]
Heh, I love it! OK, no new feature discussion until then, and *hopefully* no bugs either.

**Comment by JNechaevsky** [comment]
Yeah, though it's not the real _"point of attention"_, I'll briefly mention it in the last line of  DoomWorld post. Guess I'm... Ahem, too old and too adult for turning my personal fads into eye-catchers. 

Thanks again for your correction. This gave me extra small boost of motivation, I'll try to experiment a little more, maybe there is even no need for introduced `savename`. Just need to don't break it again!
