### ISSUE TITLE
Gameplay features/default skill level option not highlighted.

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#119]
Hi Julia.

I have found a tiny "issue" in Inter-Hexen, Heretic and DOOM.
Gameplay features, page 3, the default skill level options (normal, hard...) are not highlighted/glowing when selected.
Everything is shining except that option.

Just for the case it's not meant to be so and you've forgotten.

**Comment by Meerschweinmann** [comment]
It is really no problem for me when it is meant to be so.

I wondered only why this option does not glow and shine,
because as far as i know you from here, you want every pixel in perfect condition :)

So i thought that you could have forgotten it and wrote it down here.

**Comment by Meerschweinmann** [comment]
Even if some people wouldn't have noticed it, now it is uniformly perfect to the rest of the menu. Those details like the glowing shadowed letters show how many love and effort you put in your ports. Thanks for that :)

**Comment by JNechaevsky** [comment]
Yeah, I remember now, there were problems with olive color previously, but after some fine-tuning I got it working.
Thank you for this boost of motivation, now all the pixels are happy. 🤗 Unfortunately, even in true color render, HSV coloring is still relied on palette colors, that's why fading looks slightly different in all three games.

**Comment by Meerschweinmann** [comment]
That is what i thought, that the paletted colors are used, because the steps in Hexens green between normal and easy remembered me as i converted DOOMs textures to Hexens palette. The green BIGDOOR had the same tint then. 
But that is no problem. The menu looks nice and that is what counts :)

Btw, speaking of palettes. Here has someone found out the same you found out with Hexens COLORMAP. You can read it above the Hexen palette. https://zdoom.org/wiki/Palette
