### ISSUE TITLE
Doom: blinking Tower of Babel

### ISSUE THREAD

**Issue by JNechaevsky** [JNechaevsky/international-doom#122]
@fabiangreffrath, @rfomin, @bradharding,

Colleagues, I'm seeing things... And issue this happens across all our ports. Have a look at the tower, it's blinking for one frame, right before intermission screen goes to next stage, i.e. to `WI_initShowNextLoc()` and drawing "you are here":

https://github.com/JNechaevsky/international-doom/assets/21193394/7e4345ef-771d-49fa-83be-2f760f074765

Easiest way to see it is to finish E2M7. If I'm getting it right, this is happened because of [this](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/wi_stuff.c#L798) line - it re-sets animation elements. And in fact, it shouldn't be called again in `WI_initShowNextLoc()`, since all animations are set on initial initializations of [single player](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/wi_stuff.c#L1359-L1368), [deathmatch](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/wi_stuff.c#L899-L923) and [coop](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/wi_stuff.c#L1119-L1142). So the fix in this case should be as simple as:

```diff
+++ wi_stuff.c
@@ -791,15 +791,15 @@
 	return;
     }
 
     state = ShowNextLoc;
     acceleratestage = 0;
     cnt = SHOWNEXTLOCDELAY * TICRATE;
 
-    WI_initAnimatedBack();
+    // WI_initAnimatedBack();
```

**Comment by bradharding** [comment]
Nice find Julia! Thanks! I'll be sure to make this change in DR.

**Comment by JNechaevsky** [comment]
My pleasure! But please, do not use my suggested approach - I just woke up with a though, that this way Fortress of Mystery will not be able to appear when entering E2M9, and yes, it didn't happen. 😕

Safest way will be to use some kind in incoming boolean for `WI_initShowNextLoc` to see if E2's animations should be reset or not.  But most likely it will not fix 100% of issue, since if animation will be reset/reinitialized upon entering _only_ Fortress of Mystery (to make it possible to appear), Tower of Babel's icon will blink, but only when entering E2M9. Totally mind blowing stuff! 

I'll investigate it deeply today, pardon me for being too fast on suggestion.

**Comment by JNechaevsky** [comment]
And done! This correction should also fix animation reset for other graphics upon switching to "Entering" state, like:
* Blinking lights on episode 1, though it is **extremely** hard to notice.
* Red sky scrolling on episode 3. This is much easier to see on taking a closer look.

And yes, it is demo-safe, as there is nothing happening with "skipping" states. Hooray! 🥳
