### ISSUE TITLE
Play Freedoom with DOOM assets.

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#123]
Hi Julia :)

Not an issue, but an Idea for a feature.

I have made an pwad to play freedoom1 and 2 with DOOM assets, because with DOOM monsters and weapons it looks more familiar.
This pwad contains nearly all Sprites (incl weapons) and all Sounds (except music) from DOOM2.

When playing Freedoom with this pwad the result is like a Megawad with new Levels, textures and music.

What do you think about an option for Inter-DOOM to use DOOM assets from DOOM.WAD or DOOM2.WAD for Freedoom? 

Optional with or without changing textures, because the Freedoom textures are really nice. That could be another point that differs Inter-DOOM from other ports.

Of course, this assumes that you own DOOM and not just Freedoom.

**Comment by Meerschweinmann** [comment]
Tiny update to explain what could be loaded from DOOM/DOOM2.WAD

All sounds, except music.

STKEYS0 to STKEYS5 to match the HUD-key-symbols with the changed skull/keycard sprites laying around in the levels.

Everything between S_START and S_END. 
Here it is debatable if TRE1A0, TRE2A0, SMITA0 and SMT2A0 should be excluded from loading from DOOM/DOOM2.WAD, because with Freedooms trees the vegetation looks sometimes more filled.

With this selection Freedoom looks like a DOOM Megawad with new levels, textures, HUD and music.

![DOOM03](https://github.com/JNechaevsky/international-doom/assets/116672360/f9025a0f-2f6f-44e5-bf3d-63dbff1e3a69)

**Comment by Meerschweinmann** [comment]
Today i got this thing in mind again and had an idea how to activate the DOOM sprites and sounds in Freedoom without new menu-option.

Simply by loading both IWADs (freedoom1.wad and DOOM.wad for example) with Inter-DOOM. 

Inter-DOOM has to know that these combination of WADs should handle freedoom.wad as IWAD and the DOOM.WAD as pwad and load the sprites and sounds from the DOOM.WAD. 
Because why else should someone load both IWADs?

**Comment by JNechaevsky** [comment]
I'm afraid I don't get it correctly. Does means "both IWADs have to be loaded, but resources have to be used separately and selectively from both of them"?

**Comment by Meerschweinmann** [comment]
Yes, you got it correct. When Inter-DOOM is loaded with "-iwad freedoom1.wad -file doom.wad" for example, Inter-DOOM should know how to handle the DOOM.wad in this Special case and load only selected parts of it.

**Comment by JNechaevsky** [comment]
Sounds a bit horrific, may lead to a bunch of possibly unclear conditions. 😕 What if different mod author will decide using different combination of loaded assets in such case? And does Crispy Doom handles it?

**Comment by Meerschweinmann** [comment]
I would say If someone uses DOOM.wad and Freedoom.wad assets then there would be possibly a third wad as map data.  In this case the crossloading should not bei allowed.
Otherwise to be safe it should only bei activated with an option in menu, config or commandline.

**Comment by Meerschweinmann** [comment]
Or an "Load monsters and weapons from DOOMx.WAD" option, that not only works with Freedoom.

**Comment by JNechaevsky** [comment]
Well... Please don't get me wrong, but this is something obscure. A very specific case that's mod author wants to be solved by source port side. Better to avoid such "exclusive" situations on mod author side, so the mod itself will be fairly playable in any source port.

**Comment by Meerschweinmann** [comment]
No problem, as i wrote in my first post i have generated a pwad to play Freedoom with DOOM monsters and weapons.
So i have a solution by hand to do that.

The Idea as a feature came up, because at Doomworld someone asked how to do that. And as i saw that there are others interested in playing Freedoom this way, but without knowledge how to use Slade3, i thought that could be an Idea for a feature.

I am totally fine If you say you will not so such things.

**Comment by Meerschweinmann** [comment]
@NightFright2k19 Sure it is not hard to do for everyone who is knowing SLADE3 basics.

Simply mark every sound, every ST.... lump and everything between S-START and S_END from DOOM2.WAD in SLADE3, copy it in a new pwad and you get what you need to play Freedoom with DOOM sprites, sounds and HUD.
That is the way i do it.

The same you should do with Freedoom.wad to generate a pwad to play DOOM with Freedoom monsters, sounds and HUD. The CWILxx lumps with the map-names will be loaded from the iwad used.
I don't think that you have to use DEHACKED this way.

As i wrote, me personally do not really need such a feature.
But as i saw at a Doomworld thread that there are other people that are interested in playing Freedoom with DOOM assets, i thought that could be a optional feature for those playing Freedoom with Inter-DOOM and owning DOOM/DOOM2.WAD.
