### ISSUE TITLE
add '-shotdir' command line parameter

### ISSUE THREAD

**Issue by liPillON** [JNechaevsky/international-doom#125]
There's people (like me) that use the '-savedir' parameter to specify custom savegame folders (tipically, dedicating one to each iwad/pwad combo).
With other ports we can do the same with screenshots by using the '-shotdir' parameter, thus saving all content generated by the same play session being in the same directory.

It would be nice if inter-doom/heretic/hexen made this possible as well, either by forcing screenshots to be written to the same folder as the savegames (when the user has specified a custom/specific one) or by adding the '-savedir' parameter proper.

Thank you!

**Comment by JNechaevsky** [comment]
Hi @liPillON, thanks for suggestion! I'm not very active on Inter last days, Heretic and Hexen drained out me completely, but this should be definitely possible. Ideally, by logics:
* Config file variables for all three games.
* And if `-shotdir` or `-savedir` is presented as command line parameter, then use provided path.

But please do not expect it soon. 🙂

**Comment by liPillON** [comment]
sure, I understand

thank you again for these fantastic LR ports
