### ISSUE TITLE
Bunny-screen seems to not like 16:9 aspect ratio

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#138]
Hi Julia.

I have found something strange. On my ultrawide monitor at home and my 16:10 notebook DOOM's Bunny-screen works as intended.

But today i was on another PC with an 16:9 monitor and, because i have been playing around with widescreen assets, i found out that everytime DOOM wants to show the Bunny-screen, the game closes without warning.

When i choose another aspect ratio as 16:9/match screen on that PC, the Bunny-screen works.

That happens to me with Version 7.4 and the actual dev-build.

**Comment by Meerschweinmann** [comment]
Can confirm that this happened on my 16:10 notebook too, when i set an aspect ratio of 16:9.

**Comment by Meerschweinmann** [comment]
Have to add once more. It happens only when 4x or 6x resolution is chosen. 3x and 5x are fine.

**Comment by JNechaevsky** [comment]
Sigh, that poor bunny again. Thank you, I was able to reproduce it. Interestingly, on my side it does not happen with widescreen assets loaded, just with stock IWAD pictures. But what is the cause - that's a question of the day. 🤤

**Comment by Meerschweinmann** [comment]
Poor Daisy :)

Yes, i could reproduce it without widescreen assets too. Sorry, forgot to mention this. Trying out without widescreen assets after the first crash was the first thing i had done, because first i thought the ws assets were the problem.
What irritates me ist that it happens with 4x resolution. 1x,2x,4x are easier to scale than 3x or 5x. Don't know how to say in english, but hope you get what i mean.

**Comment by Meerschweinmann** [comment]
I will edit the line, built new and try this. 

One thing i have noticed in another tesdt now. The crash does only occur when the first of the two bunny pictures is shown. When it scrolls and i switch from 3x to 4x res nothing bad happens.
When the first bunny picture is shown, does not scroll and i switch then from 3x to 4x it crashes.

**Comment by Meerschweinmann** [comment]
> Not very responsive today, woke up this morning with odd exhaustion like was moving crates all the night.

Had first to translate what that means. I know exhausts from cars :)
I hope it is nothing bad and wish you a speedy recovery.

**Comment by Meerschweinmann** [comment]
Your solution with the bunny screen works. I have switched through all resolution before the bunny screen scrolls and did not get a crash.
When i did that before that change it crashed.

**Comment by JNechaevsky** [comment]
Yeah, just tried same way, with and without assets: once bunny screen appears and later scrolls, I simply was holding a finger on rendering resolution changing. What was going on? Honestly, no idea. This function was written by Michael for Crispy Doom where there is no > 3x resolutions. I just briefly looked through the function and thought what can possible happens. Yeah-yeah, this is exactly how ~~programming~~ magic is working! 😅

I'm fine, nothing bad happened. Probably just need to be on a fresh air more often, not just on weekends.
