### ISSUE TITLE
Saving games suddenly stopped working.

### ISSUE THREAD

**Issue by sebastian926** [JNechaevsky/international-doom#147]
![Captura](https://github.com/user-attachments/assets/39145b46-adea-4c35-8eb0-8db2b527c5bb)

**Comment by sebastian926** [comment]
It says open save game, but the truth is that it doesnt let me save. It didnt happen before a few days ago, which is weird.

**Comment by JNechaevsky** [comment]
Something went terribly wrong while writing savegame file, it's weird indeed. Could you please check if `temp.sav` and/or `recovery.sav` file exist in `savegames` folder, and if they do, delete them.

**Comment by sebastian926** [comment]
Oh sorry, i discover the real issue here. It seems that i accidentally changed the folder name and the save location is tied to an ini file. So that ini file didnt detected the original location. Thanks anyway.

**Comment by JNechaevsky** [comment]
Good to know, thanks! If you want fully portable paths in the config file, you can try these:
```
autoload_path                 "autoload"
music_pack_path               "music-packs"
savegames_path                "savegames"
screenshots_path              "screenshots"
```
