### ISSUE TITLE
No `-levelstat` in Inter-Doom?

### ISSUE THREAD

**Issue by xemonix0** [JNechaevsky/international-doom#154]
Inter-Doom seems to lack an implementation of `-levelstat` and only has `-statdump` (Crispy Doom has both). Inter-Heretic does have `-levelstat`, which is why I assume it's an oversight and not something intentional.

**Comment by JNechaevsky** [comment]
Yes, absolutely not intentional. Despite of Inter have much code from Crispy, it's not a direct fork of Crispy and some things like this one are simply wasn't ported. But no problem, I will merge `-levelstat` shortly, thanks for suggestion!
