### ISSUE TITLE
Coloured ammo widget

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#45]
I started working on colourizing the ammo widget, but thought I should ask for your opinion on some questions. Here's a mockup:

![HTIC04](https://github.com/JNechaevsky/international-doom/assets/47063032/366faa5c-25ab-4986-81fd-6a1b261ff322)

Questions:
- Do we want an option for doing this, or is it enough to colour it if "colored elements" for the statusbar is on?
    If we want a separate option, it should probably be split into "ammo+weapons", "ammo only", "weapons only" items, I think. (Here I am colourizing the weapon letter for weapons that the player has).
- Do 0s for 'no ammo' get coloured? They should to be consistent with the way statusbar/hud ammo is I guess.
- Should the ammo totals be colourized as well for the full widget? (Coloring the slash but not the total like I did here looks bad, that can be changed easily though.)
- I would like to add some indication if the player has the gauntlets. Adding a 'g' is easy enough, but then it only makes sense for it to always appear if the weapon letters are coloured. Also, should it go above or below the other weapon/ammo lines?
- Any other thoughts?

**Comment by JNechaevsky** [comment]
Thanks for asking. 🙂 I was thinking about coloring, but almost immediately rejected this idea - if it's will be done in just one menu item, then it will lead to confusion about amount of available items, there will be too much. But thinking more, it will be completely okay if extra options will be divided to something like this:

**AMMO WIDGET**
Indication: off / brief / full
Translucency: off / on
Coloring: off / on

This will require two extra config variables of course.

> Do we want an option for doing this, or is it enough to colour it if "colored elements" for the statusbar is on? If we want a separate option, it should probably be split into "ammo+weapons", "ammo only", "weapons only" items, I think. (Here I am colourizing the weapon letter for weapons that the player has).

Better separate coloring to own function, as ammo widget is not related to status bar itself. As about options, yep, feels pretty decent and fixable. 

> Do 0s for 'no ammo' get coloured? They should to be consistent with the way statusbar/hud ammo is I guess.

If any kind of ammo coloring is used I guess.

> Should the ammo totals be colourized as well for the full widget? (Coloring the slash but not the total like I did here looks bad, that can be changed easily though.)

Yes, that's would be ideal to colorize full string, i.e. `current/max`, not just `current/`.

> I would like to add some indication if the player has the gauntlets. Adding a 'g' is easy enough, but then it only makes sense for it to always appear if the weapon letters are coloured. Also, should it go above or below the other weapon/ammo lines?

Oh, not sure about it. It's primary ammo, not weapon widget, and having gauntlets will not prevent choosing staff. Maybe it is worth to don't add it and keep line beauty?

> Any other thoughts?

Yes, please, just keep things simple. 🙂 Separated utility functions for coloring will help a lot for simplification (like original [STbar coloring](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/sb_bar.c#L987)). My previous implementation was working fine in the game, but under the hood it's a ... Ahem, let's just call it [mess](https://github.com/Russian-Doom/russian-doom/blob/master/src/heretic/sb_bar.c#L2761).

**Comment by kitchen-ace** [comment]
Thanks! I'll take a crack at it today.

Also to be clear: you definitely don't need to accept this, or any feature, if you don't feel it fits. I know you have certain overall goals for this port; there will be no hard feelings if you reject or decline any ideas or contributions I make.

**Comment by kitchen-ace** [comment]
>Separated utility functions for coloring will help a lot for simplification (like original [STbar coloring](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/sb_bar.c#L987))

OK to make a new function for this, instead of trying to extend SB_NumberColor?
