### ISSUE TITLE
Segfault on opening automap

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#46]
Playing Quoth the Raven:
https://www.doomworld.com/idgames/levels/heretic/Ports/puss28_qtr

Starting the game, loading this save, and then trying to view the automap causes a segfault. 
[hticsav1.zip](https://github.com/JNechaevsky/international-doom/files/13942506/hticsav1.zip)

If I load the save, start a new game, then load the save again, the automap works fine.

My ini settings in case it matters:
[inter-heretic.ini.txt](https://github.com/JNechaevsky/international-doom/files/13942519/inter-heretic.ini.txt)

**Comment by JNechaevsky** [comment]
Uh-oh. I can't reproduce crash, but it seems that `AUTOPAGE` gets into `PU_STATIC` vs `PU_CACHE` problem, [here](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/am_map.c#L347) and [here](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/am_map.c#L1135). Could you please check if commit https://github.com/JNechaevsky/international-doom/commit/6b3438eb5a4a0745ab2d9c49f906786904526824 helps?

**Comment by kitchen-ace** [comment]
Unfortunately with that commit, the save just crashes immediately on load.

However if you think that will prevent the problem in the future, it's fine, it's not important to me that that savegame gets preserved.

**Comment by JNechaevsky** [comment]
Not sure if it is possible to do something about save. 😕 But does it's reproducible w/o using corrupted save on your side?

**Comment by kitchen-ace** [comment]
I haven't been able to reproduce it otherwise; I had used the automap on that level previously, and have been through the previous 24 maps without issue, checking the map at least occasionally.

**Comment by kitchen-ace** [comment]
Closing this for now, will reopen if I encounter it again.

**Comment by JNechaevsky** [comment]
Sure, thank you again. It should be fine, I'm sure as I made such oversights previously.
