### ISSUE TITLE
[Feature] Automatic centering of widescreen statusbars

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#58]
While using widescreen replacements for menu graphics seems to work, widescreen statusbars without offsets ([such as these](https://github.com/NightFright2k19/doom_widehud)) are currently not properly aligned, at least when using last official build (7.3). Might also apply to Heretic (couldn't test).

![DOOM00](https://github.com/JNechaevsky/international-doom/assets/54737241/fcc08377-2c4f-4f06-a78b-d8f8ab23c66a)

**Comment by NightFright2k19** [comment]
![DOOM00](https://github.com/JNechaevsky/international-doom/assets/54737241/137cb921-f851-40c0-8b1f-d7f41301c93d)

**Comment by JNechaevsky** [comment]
Thank you! Should be fixed now, looks likes I was using non-zero left offset wide status bar all this time. Heretic should be fine as it [supports](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/sb_bar.c#L803) such offset already.

P.S. Lovely archive, amazing efforts! 👍
