### ISSUE TITLE
[Feature/Bug] Mousewheel on Inter-Heretic automap

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#59]
Seems as if in Inter-Heretic, using the mousewheel rather cycles through weapons instead of zooming in/out.

**Comment by JNechaevsky** [comment]
Honestly, never thought it is usable until finally tried it out. Sure, will gladly port it from Crispy Doom to both Doom and Heretic, so zooming speed will be identical and familiar. 🙂
