### ISSUE TITLE
[Feature] Heretic automap color for secrets

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#63]
Secrets in Inter-Heretic are shown as grey lines on the automap. While this works well in Doom with a black background, this is less the case in Heretic's (and Hexen's) map with its pergament look.

Originally, IIRC secret automap lines in Heretic used to be black. While this makes them kinda hard to distinguish from regular lines, it definitely works better than grey. Maybe white could be tried instead if a return to the original color isn't desired. 

Since there doesn't seem to be a way to customize automap colors for drawn lines (at least I haven't seen any in the ini file), this would actually be kinda important in order to not having to glue your face too close to the screen to spot those elusive little secret areas. :)

Screenshot to illustrate the issue:
![HTIC00](https://github.com/JNechaevsky/international-doom/assets/54737241/016dc153-e446-41e2-9e38-d308e111d984)

**Comment by JNechaevsky** [comment]
Ah, so it is vanilla behavior with map scroll lines revealing. But no doubts, it should be improved, as whole this port stands for such things. Colors can remain same in overlay mode (when background is darker) and darken in normal mode (parch background). Smoothing will be a nice addition. 👩🏻‍🎨

<details>

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/47c1de9b-215e-403b-a34e-c7fd1550767b)

</details>

**Comment by JNechaevsky** [comment]
Seems to be nice? Could be slightly darker for one color, but then it probably will be too dark and harder to distinguish from normal walls. No changes in overlay mode, though.

<details>

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/c2771a3f-ecf5-417b-9870-06e90a4e6f86)

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/52045fc2-b539-4cf4-b2dc-21e7ce7fabc7)

```diff
@@ -294,7 +294,7 @@
     {110, 109, 108, 107, 106, 105, 104, 103},   // FDWALLCOLORS
     { 75,  76,  77,  78,  79,  80,  81, 103},   // CDWALLCOLORS
     { 40,  40,  41,  41,  42,  42,  43,  43},   // MLDONTDRAW1
-    { 43,  43,  43,  42,  42,  42,  41,  41},   // MLDONTDRAW2
+    { 40,  40,  41,  41,  42,  42,  43,  43},   // MLDONTDRAW2
     {143, 143, 142, 142, 141, 141, 141, 141},   // YELLOWKEY
     {220, 220, 219, 219, 218, 218, 217, 217},   // GREENKEY
     {197, 197, 196, 196, 195, 195, 194, 194},   // BLUEKEY

```

</details>

**Comment by NightFright2k19** [comment]
Yes, a lot more pleasant to the eye. :) Make it so!
