### ISSUE TITLE
Hexen: drawsegs overflow

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#66]
not sure which commit it was but one of the new ones is now giving me lots of game ending errors
`R_DrawPlanes: drawsegs overflow (###)`

using `-warp 7` should trigger it easily if you wander around the map, here's a savegame that will trigger it if you just strafe left a bit:
[hex0.zip](https://github.com/JNechaevsky/international-doom/files/14157340/hex0.zip)

**Comment by JNechaevsky** [comment]
Yeah, incorrect leftover check. Please try to use [hxn_optimize](https://github.com/JNechaevsky/international-doom/tree/) branch, or just wait ~30 minutes, I'm finishing with limit-removing stuff.

**Comment by JNechaevsky** [comment]
All done and merged into `main` branch. 🙌 There still might be some play state limits (ambient sounds and etc.), but it shouldn't be that important. But render optimizations seems to be all set.

**Comment by kitchen-ace** [comment]
Looks good, sorry for jumping the gun!
