### ISSUE TITLE
[Feature] Rename "Fly Center" keybind

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#70]
IMHO, the title for the "Fly Center" keybind (Heretic/Hexen) is a bit misleading. What it actually does is to interrupt flight mode. Therefore, something like "Fly Stop" or "Fly Pause" (to fit with "Fly Up"/"Fly Down") would be more helpful (also since it's actually a rather important function, which isn't obvious with the current title).

**Comment by JNechaevsky** [comment]
It comes directly from [Chocolate Doom](https://github.com/chocolate-doom/chocolate-doom/blob/master/src/setup/keyboard.c#L222) setup. Have to agree, it's look odd... Probably "Stop fly" or "Land" will be more suitable? Deffinitly worth to ask @kitchen-ace for recommendation as English not my native language.

**Comment by kitchen-ace** [comment]
"Fly Center" is indeed vanilla terminology, but preserving that here isn't necessary. 

"Stop Flying" is the most natural sounding term IMO, and also what ZDoom uses.

**Comment by JNechaevsky** [comment]
So be it then. 🙂 Small cross-port identity, especially for such things, seems to be very reasonable.

**Comment by NightFright2k19** [comment]
Great! I wasn't aware this was vanilla terminology. But well, it's merely a menu entry without any consequence ingame. Thanks for implementing!
