### ISSUE TITLE
[Feature/Issue] Automap keys on TNAWN

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#72]
When playing on the lowest difficulty in Heretic, the location of keys is apparently not shown on the automap. A comparison with Crispy Heretic shows that it works there. Is this an intended change that needs to be manually activated via setting?

In any case, this should be on by default since [it's a vanilla feature](https://doomwiki.org/wiki/Skill_level#Heretic_skill_levels).

**Comment by JNechaevsky** [comment]
Uh-oh, it's not an option - keys drawing did not survived heavy automap upgrade. It is easy to fix, and probably original colors needs some refinement, as in current implementation green and blue looks a bit too dark, it can be better.

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/b4c1708c-3202-499d-a5ba-a4342f48177e)

Thanks for pointing out!

**Comment by NightFright2k19** [comment]
Wonderful. It's only a thing in Heretic, though. Hexen doesn't seem to have it.

**Comment by JNechaevsky** [comment]
Should be fine now, thanks again. Hexen doesn't show keys indeed, whole function and it's call are [commented out](https://github.com/chocolate-doom/chocolate-doom/blob/master/src/hexen/am_map.c#L1401) in the code. Speaking of Inter-Hexen automap, there is still some potential for better lines smoothing in overlay mode, plus smoothing some extra line types. I haven't investigated it yet, just made it working. At the moment I'm focused on filling Gameplay Features.

**Comment by NightFright2k19** [comment]
What could also be considered: Somewhat thicker automap lines in higher resolutions. I'd say starting at 600p and higher. Maybe you could experiment with 2x thickness and see what it looks like.

**Comment by NightFright2k19** [comment]
Well, since I stick to 600p, for me this isn't a big deal, anyway.
