### ISSUE TITLE
Hexen: mouse slider can't go up past 9

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#75]
Unlike the other inter-ports, you can't move the slider in the mouse controls menu further than 9. It still works fine if you set it manually via config editing.

**Comment by JNechaevsky** [comment]
Thank you! Out-of-bounds slider's gem code was already [here](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/mn_menu.c#L5053), but extended range itself for mouse sensitivity was missing.
