### ISSUE TITLE
[Bug] Inter-Doom and menu background shading

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#81]
There is an issue with latest build of Inter-Doom and "Menu Background Shading". As soon as you turn it on, the statusbar will flicker like crazy during demo playback. The effect gets worse the higher you set the value.

Issue only affects Doom. Heretic and Hexen work fine.

**Comment by NightFright2k19** [comment]
Geez, that was fast! Thanks a lot and a nice Sunday!

**Comment by JNechaevsky** [comment]
Thank you! No need to wait to fix such things. 🙂

Next plans:
- Hexen: review automap line smoothing in overlay mode, they can be better as well as all line types (locked doors and teleporters) can be smoothed.
- Hexen: randomly mirrored corpses. Aside from corpses, few extra things can be flipped as well, like Ettin's maces and Centaur's shields.
- Hexen: settings reset, as all features seems to be on place.
- Hexen: graphical startup (optional, should be disabled by default). It was commented out in the code while initial Hexen implementation, but should work fine.
- Shading needs some revisiting in all games, like in menus covered with flat backgrounds - probably to apply shading there as well for consistency. 
- Menu "Y" confirmation by pressing left mouse button and "N" by pressing right button. For now, menu can be easily traveled by mouse, but this case still requires pressing "Y" on keyboad.

Also, I have updated common vanilla and save/load menus with line highlighting/fading effect. It should be safe for mods (primary critical for Doom), but.. I would like to hear impressions, is it okay or is it too much? Friendly ports already have such highlighting, so there is nothing extra new, except fading effect. Kindly asking for @kitchen-ace and @Meerschweinmann opinions too, the code has been merged already.

**Comment by NightFright2k19** [comment]
I think it's soon time to do a Hexen playthrough, see of everything where it's supposed to be. A pity there are next to zero Hexen PWADs, and if there are any, they are often GZDoom only.

**Comment by Meerschweinmann** [comment]
Hello at all :)
I have built a new ID and can confirm that the vanilla menu part highlighting and fading when i select menu options looks very good. I like it. A nice detail.

Yeah, unfortunately Hexen vanilla or limit removing pwads are very rare,
but Inter-Hexen preserves me the Hexen i knew in software rendered higher res, truecolor and nice new faithful features on todays hardware. That is everything i need.
