### ISSUE TITLE
[Feature] Inter-Doom not auto-filling save slot name

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#90]
When saving your game, Inter-Doom does not automatically enter the name of the current map into the savegame slot. For consistency reasons with Inter-Heretic/Hexen, this should probably be adjusted.

**Comment by JNechaevsky** [comment]
Please take a try now. This is simplest way, as it does not write (I/P)wad name, similar to Heretic and Hexen save names handling.

**Comment by NightFright2k19** [comment]
Looks good to me. It's a bit overdone in Crispy. Level name is fully sufficient.

**Comment by JNechaevsky** [comment]
So be it then. 🙂 I was trying to keep vanilla menu as long as possible to vanilla, but got used to such autonaming in Raven games plus recent changes with menu highlighting makes a huge difference.
