### ISSUE TITLE
[Feature] Hexen: Brightmaps for "glitter bridge" sprites

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#95]
Would be cool if these glitter sprites which build kinda "magical" bridges would have brightmaps, too.

![HEXEN00](https://github.com/JNechaevsky/international-doom/assets/54737241/a4871815-9ad2-4b4f-b68c-72a9b1c77110)

**Comment by JNechaevsky** [comment]
Isn't _too_ bright, comparing to other dull Hexen palette and assets? 🙂

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/45044642-6f3f-40f2-a627-b5afc99fe774)

You can quickly check it out on your side, it's pretty simple:

```diff
+++ inter-doom/src/hexen/r_bmaps.c
@@ -249,6 +249,12 @@
     {
         switch (state)
         {
+            // Glitter bridge
+            case S_BBALL2:
+            {
+                return fullbright;
+                break;
+            }
             // Banishment Device
             case S_ARTI_TELOTHER1:
             case S_ARTI_TELOTHER2:

```

**Comment by Meerschweinmann** [comment]
Sparkling bright glitter bridges are a nice idea!

**Comment by NightFright2k19** [comment]
Make them shiny, baby!

**Comment by JNechaevsky** [comment]
Allright, allright! 😀 So be it then. Just verified - yep, Heretic is using full bright effect for teleport glitters.

**Comment by NightFright2k19** [comment]
Absolutely brilliant. Julia for president!

**Comment by Meerschweinmann** [comment]
Hooray, that is a nice addition :)

**Comment by NightFright2k19** [comment]
I'm currently doing a full playthrough of the original campaign. Should I find anything else, I'll let you know.
