### ISSUE TITLE
[Feature] Inter-Hexen: Customizable savegame path

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#96]
It seems I'm unable to change _savedir_ path in inter-hexen.ini. Whatever I put there, it wouldn't find my savegames unless the default directory (Inter-Hexen dir\savegames) is used. Also, any edits made would be reverted to default whenever the game is launched. 

Also, relative dirs apparently aren't supported, e.g.

```
autoload_path                 "autoload"
music_pack_path               "musicpacks"
```

Always uses full path instead, i.e.
`savedir                       "C:\Games\Doom\sourceports\inter-doom\savegames\"`

Since Hexen produces a lot of savegames, even if user is only creating one or two by themselves, it'd be great to be able to create a subdir to separate them from the rest, i.e. Doom and Heretic.

**Comment by JNechaevsky** [comment]
`savedir` path should be fixed now. As about other games, well, historically I have nothing more that headache with such variables, and not sure I can do it right for Doom and Heretic. If needed, savegames can be safely deleted in all three games now.
