### ISSUE TITLE
Hexen sfx attenuatian axis

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#98]
Helloho :)

i was not sure if the sfx attenuation axis option is not in the Inter-Hexen menu, because Hexen as the most advanced ID-Tech1 game from those three could have the feature built in by default.
So i made a short test with a dark bishop 1920 pixels above me.

The result was, that there is no difference when i stand next to the dark bishop or 1920 pixels below him.

For the case this feature is on your list and i was too early in checking this you can ignore this.

**Comment by JNechaevsky** [comment]
At the moment, we are out of room on both Gameplay pages for "Audible" subheader and "SFX attenuation" item... 
🫲🤤🫱

**Comment by JNechaevsky** [comment]
All done! And thanks for suggestion and motivation!

**Comment by Meerschweinmann** [comment]
Hooray. If someone has to say thank you, it is me :)
