### ISSUE TITLE
[Bug] Inter-Hexen: Can't save

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#99]
It seems something went horribly wrong [with this commit](https://github.com/JNechaevsky/international-doom/commit/f67c4e9b0cd54f5357cc13fc3824e6fb3cc71b98). Now you are unable to save WHEN you are playing... ;)

**Comment by kitchen-ace** [comment]
The check on this line needs changing:
https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/g_game.c#L2337

```
    // [crispy] since demoextend is the default, we also want to check to
    // make sure we're not playing a demo
    if (!demoextend || (!demorecording && !demoplayback))
```

**Comment by JNechaevsky** [comment]
Oh, dang, but somehow saving was working on my end. 😨 Thanks, I'll fix it now.

**Comment by JNechaevsky** [comment]
As magical as it gets. I swear, saving was working at my end! Thanks again, everything should be fine now.

**Comment by NightFright2k19** [comment]
Phew! I was afraid the mysteries of the second hub would always remain hidden from me due to this. XD Much obliged!

**Comment by JNechaevsky** [comment]
I remember someone was calling Inter-Doom a replacement for Unity port. Guess, we now can go this way. 🤪

![image](https://github.com/JNechaevsky/international-doom/assets/21193394/e76b82de-3bf7-47cd-9a4e-b7f637fd24f9)

**Comment by NightFright2k19** [comment]
Feature request: Each hub, ah, what the heck, each MAP only unlocks after a transfer of 25 bucks to your Paypal donation account (or whatever you're using these days)... xD

**Comment by JNechaevsky** [comment]
> or whatever you're using these days

Nothing, literally. Our _"wünderland"_ is cut off from world-wide payment system. And the farther this whole idiocy goes, the deeper shit becomes. The thing what happened last Friday is yet another nail into the sanity's coffin and, probably, small hope for better future. Fortunately, I have no need for donations or something, and keeping myself highly isolated literally from everything and everyone, there are just two thing is my life: my wife and my source port. 🙂

**Comment by Meerschweinmann** [comment]
> > or whatever you're using these days
> 
> Nothing, literally. Our _"wünderland"_ is cut off from world-wide payment system. And the farther this whole idiocy goes, the deeper shit becomes. The thing what happened last Friday is yet another nail into the sanity's coffin and, probably, small hope for better future. Fortunately, I have no need for donations or something, and keeping myself highly isolated literally from everything and everyone, there are just two thing is my life: my wife and my source port. 🙂

As i know where you life, i am careful with political statements everybody can read, because no one knows who can read this. And i don't wan't you to get in trouble like many other people. The most known died these days... I am glad to read that you have found your way, a person and things that make you happy in those times. And it is "Wunderland" in german :)

**Comment by kitchen-ace** [comment]
May sane minds prevail, and better sooner than later.
